### ISSUE TITLE
clang2py installation on Windows: clang>=3.7

### ISSUE THREAD

**Issue by rchateauneu** [trolldbois/python-haystack#28]
I try to install clang2py as indicated here:
https://pypi.python.org/pypi/ctypeslib2/2.1.4

There is a dependency problem for clang >=3.7 and a workaround for Unix. But what must be done for Windows ? Here is the result of the pip install:

C:\Users\rchateau>pip install ctypeslib2
Collecting ctypeslib2
  Downloading ctypeslib2-2.1.4.tar.gz (46kB)
    100% |################################| 51kB 1.7MB/s
Collecting clang>=3.7 (from ctypeslib2)
  Could not find a version that satisfies the requirement clang>=3.7 (from ctypeslib2) (from versions: 3.3-svn191928, 3.2, 3.3, 3.4.
dev192547, 3.4, 3.5, 3.7.dev234764, 3.7.dev234765)
No matching distribution found for clang>=3.7 (from ctypeslib2)

**Comment by trolldbois** [comment]
python-clang is not distributed by upstream using pip.
the pypi package is (sadly) mine and had not been updated in a while :(

http://clang.llvm.org/get_started.html
http://llvm.org/releases/download.html

you will need to follow's LLVM Clang instruction for windows, and install the python bindings from there. I honestly have no idea if the python bindings are distributed in the clang windows install.
You might have to install the python bindings from LLVM clang source.

I will publish an updated python-clang from upstream on pypi when I have 5 minutes

**Comment by trolldbois** [comment]
what about now ?

**Comment by trolldbois** [comment]
I take it this is solved

**Comment by rchateauneu** [comment]
Yes, sorry for the late answer. Writing by hand ctypes file is a good
solution because one can focus on constraints etc...

**Comment by GERMANOCARELLA** [comment]
Sorry, maybe I wrong something. I installed ctypeslib2 from pypy and I ran clang2py on windows. I ran clang2py test.h but clang2py goes into infinite loop and doesn't close. Where I can find a clang2py version for windows? There is a link?

**Comment by trolldbois** [comment]
Sorry, I won't be able to support for a few months. Can you try to pinpoint
the bug ? Get more logs ? ( Debug option )
